<template>
    <div class="loading_container" v-if="loading">
        <div class="loadingio-spinner-double-ring-eusaiviiguj"><div class="ldio-ifo9mf0t1u">
          <div></div>
          <div></div>
          <div><div></div></div>
          <div><div></div></div>
          </div>
        </div>
      </div>
</template>

<script>
// import {ref} from 'vue'

export default {
    name: 'LoadSpinner',
    props: ["loading"]
}
</script>

<style>
/* Loader */
@keyframes ldio-ifo9mf0t1u {
    0% { transform: rotate(0) }
    100% { transform: rotate(360deg) }
  }
  .ldio-ifo9mf0t1u div { box-sizing: border-box!important }
  .ldio-ifo9mf0t1u > div {
    position: absolute;
    width: 187.23000000000002px;
    height: 187.23000000000002px;
    top: 24.885px;
    left: 24.885px;
    border-radius: 50%;
    border: 7.11px solid #000;
    border-color: #ca3433 transparent #ca3433 transparent;
    animation: ldio-ifo9mf0t1u 2s linear infinite;
  }
  
  .ldio-ifo9mf0t1u > div:nth-child(2), .ldio-ifo9mf0t1u > div:nth-child(4) {
    width: 168.27px;
    height: 168.27px;
    top: 34.365px;
    left: 34.365px;
    animation: ldio-ifo9mf0t1u 2s linear infinite reverse;
  }
  .ldio-ifo9mf0t1u > div:nth-child(2) {
    border-color: transparent #f9b31c transparent #f9b31c
  }
  .ldio-ifo9mf0t1u > div:nth-child(3) { border-color: transparent }
  .ldio-ifo9mf0t1u > div:nth-child(3) div {
    position: absolute;
    width: 100%;
    height: 100%;
    transform: rotate(45deg);
  }
  .ldio-ifo9mf0t1u > div:nth-child(3) div:before, .ldio-ifo9mf0t1u > div:nth-child(3) div:after { 
    content: "";
    display: block;
    position: absolute;
    width: 7.11px;
    height: 7.11px;
    top: -7.11px;
    left: 82.95px;
    background: #ca3433;
    border-radius: 50%;
    box-shadow: 0 180.12px 0 0 #ca3433;
  }
  .ldio-ifo9mf0t1u > div:nth-child(3) div:after {
    left: -7.11px;
    top: 82.95px;
    box-shadow: 180.12px 0 0 0 #ca3433;
  }
  
  .ldio-ifo9mf0t1u > div:nth-child(4) { border-color: transparent; }
  .ldio-ifo9mf0t1u > div:nth-child(4) div {
    position: absolute;
    width: 100%;
    height: 100%;
    transform: rotate(45deg);
  }
  .ldio-ifo9mf0t1u > div:nth-child(4) div:before, .ldio-ifo9mf0t1u > div:nth-child(4) div:after {
    content: "";
    display: block;
    position: absolute;
    width: 7.11px;
    height: 7.11px;
    top: -7.11px;
    left: 73.47px;
    background: #f9b31c;
    border-radius: 50%;
    box-shadow: 0 161.16px 0 0 #f9b31c;
  }
  .ldio-ifo9mf0t1u > div:nth-child(4) div:after {
    left: -7.11px;
    top: 73.47px;
    box-shadow: 161.16px 0 0 0 #f9b31c;
  }
  .loadingio-spinner-double-ring-eusaiviiguj {
    width: 237px;
    height: 237px;
    display: inline-block;
    overflow: hidden;
    background: none;
  }
  .ldio-ifo9mf0t1u {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-ifo9mf0t1u div { box-sizing: content-box; }
  .loading_container {
    position: fixed;
    width: 100%;
    height: 100vh;
    background-color: rgba(255, 255, 255, 0.78);
    z-index: 1;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  /* generated by https://loading.io/ */
</style>